### ISSUE TITLE
Finish off a template scheme

### ISSUE THREAD

**Issue by Darthpbal** [Darthpbal/homeTests#15]
We really need to make this concrete and complete this so I feel less like I've just spent a bunch of time on nothing.

### Features I want

 - [ ] Complete the code for the template I want to apply to every single page.
 - [ ] Have a way to inject variables into a page only to be used for template data, no sensitive information. Include the templace class in routes.php, pass the teamplate variable from the routes file to the view page and handle further using jQuery and JS.
 - [ ] Have every non system view file be constructed similarly with a variable somewhere on the page for identifying to the system what the current page is. 
 - [ ] Have a common place to write actual page content that won't collide with templating or other data on the page.

**Comment by Darthpbal** [comment]
## Possible old issue found!
FUCK!!! master.php is already being included into everything... This may be why I had pages that wouldn't render before. So I need to keep this master view file in here and actually use it. Try to keep main page heading and navigation templating in here. 

### TODO:
 - [ ] check to see if I can inject variables into this master file in the way that I was thinking about before.

>  - Try this by trying to pass a page template variable into the page using the routes.php file
